// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'this project is currently configured only for Android and iOS.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'this project is currently configured only for Android and iOS.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'this project is currently configured only for Android and iOS.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYZ4e6gEcAQs4yrF2Kv5KUn8oVQ4WBvls',
    appId: '1:1043689888340:android:c462759d7a168d14682bc1',
    messagingSenderId: '1043689888340',
    projectId: 'soslive-f7513',
    storageBucket: 'soslive-f7513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKO8jW74WUJZI6FDJ4zalB789xL7mV5DQ',
    appId: '1:1043689888340:ios:aba40158351f9e4c682bc1',
    messagingSenderId: '1043689888340',
    projectId: 'soslive-f7513',
    storageBucket: 'soslive-f7513.firebasestorage.app',
    iosClientId: '1043689888340-ovkd30vkto975sut4d3b9813pvvtc1f7.apps.googleusercontent.com',
    iosBundleId: 'com.SosLive.appssos',
  );
}
